In [ ]:
def luaspersegi(Panjang, Lebar):
  luas = Panjang*Lebar
  return luas
print(luaspersegi(5,6)*3)

90

In [ ]:
def luaspersegi(Panjang=5, Lebar=6):
  luas = Panjang*Lebar
  return luas
print(luaspersegi(8))

48

In [ ]:
print("kalkulator pencari luas bangun datar")
print("1. balok\n2. segitiga\n3. lingkaran\n4. exit\n5. histori")
adi = int(input("masukkan pilihan anda : "))
if (adi) == "1":
  print("kamu bahagia")

kalkulator pencari luas bangun datar
1. balok
2. segitiga
3. lingkaran
4. exit
5. histori
masukkan pilihan anda : 1

In [3]:
def celsius_to_fahrenheit(celsius):
    return (celsius * 9/5) + 32

def celsius_to_kelvin(celsius):
    return celsius + 273.15

def celsius_to_reamur(celsius):
    return celsius * 4/5

def celsius_to_rankine(celsius):
    return (celsius + 273.15) * 9/5

def konversi_suhu():
    celsius = float(input("Masukkan nilai Celsius: "))
    adi = True
    while adi:
        print("\nKonversikan dalam:")
        print("1. Fahrenheit")
        print("2. Kelvin")
        print("3. Reamur")
        print("4. Rankine")
        print("5. Exit")

        pilihan = input("Masukkan pilihan: ")

        if pilihan == "1":
            fahrenheit = celsius_to_fahrenheit(celsius)
            print(f"Konversi dari Celsius ke Fahrenheit adalah {fahrenheit}")
        elif pilihan == "2":
            kelvin = celsius_to_kelvin(celsius)
            print(f"Konversi dari Celsius ke Kelvin adalah {kelvin}")
        elif pilihan == "3":
            reamur = celsius_to_reamur(celsius)
            print(f"Konversi dari Celsius ke Reamur adalah {reamur}")
        elif pilihan == "4":
            rankine = celsius_to_rankine(celsius)
            print(f"Konversi dari Celsius ke Rankine adalah {rankine}")
        elif pilihan == "5":
            print("Terima kasih, program selesai.")
            adi = False
        else:
            print("Pilihan tidak valid, silakan pilih 1 hingga 5.")

konversi_suhu()

Masukkan nilai Celsius: 32

Konversikan dalam:
1. Fahrenheit
2. Kelvin
3. Reamur
4. Rankine
5. Exit
Masukkan pilihan: 5
Terima kasih, program selesai.

In [5]:
# prompt: dataFilm = {
#     1 : ['Deadpool & Wolverine',0, 40_000,30],
#     2 : ['Venom: The Last Ride',0, 100_000,35],
#     3 : ['Transformers: The One',0, 55_000, 35],
#     4 : ['Mufasa The Lion King',0, 35_000, 20],
#     5 : ['Gladiator II',0, 55_000, 40],
# }
# # Output Program
# Menu:
# 1. Daftar Film
# 2. Beli Tiket
# 3. Lihat Tiket
# 4. Akhiri Program
# Masukkan pilihan : 1
# Daftar Film:
# 1. Deadpool & Wolverine - Jam 13:15 - Harga: 40,000
# 2. Venom: The Last Ride - Jam 14:30 - Harga: 100,000
# 3. Transformers: The One - Jam 15:00 - Harga: 55,000
# 4. Mufasa The Lion King - Jam 17:20 - Harga: 35,000
# 5. Gladiator II - Jam 17:45 - Harga: 55,000
# Menu:
# 1. Daftar Film
# 2. Beli Tiket
# 3. Lihat Tiket
# 4. Akhiri Program
# Masukkan pilihan : 5
# pilihan tidak valid
# Masukkan pilihan : 2
# Tiket Tersedia:
# 1. Deadpool & Wolverine = 30 Tiket
# 2. Venom: The Last Ride = 35 Tiket
# 3. Transformers: The One = 35 Tiket
# 4. Mufasa The Lion King = 20 Tiket
# 5. Gladiator II = 40 Tiket
# pilih film (1-5): 3
# Masukkan Jumlah tiket: 3
# total harga: 16

dataFilm = {
    1 : ['Deadpool & Wolverine',0, 40_000,30],
    2 : ['Venom: The Last Ride',0, 100_000,35],
    3 : ['Transformers: The One',0, 55_000, 35],
    4 : ['Mufasa The Lion King',0, 35_000, 20],
    5 : ['Gladiator II',0, 55_000, 40],
}

def show_menu():
    print("Menu:")
    print("1. Daftar Film")
    print("2. Beli Tiket")
    print("3. Lihat Tiket")
    print("4. Akhiri Program")

def show_movies(dataFilm):
    print("Daftar Film:")
    for id, film in dataFilm.items():
      # Adjust the time display as needed based on your desired format
      showtime = ""
      if id == 1:
        showtime = "13:15"
      elif id == 2:
        showtime = "14:30"
      elif id == 3:
        showtime = "15:00"
      elif id == 4:
        showtime = "17:20"
      elif id == 5:
        showtime = "17:45"

      print(f"{id}. {film[0]} - Jam {showtime} - Harga: {film[2]}")


def buy_tickets(dataFilm):
    print("Tiket Tersedia:")
    for id, film in dataFilm.items():
        print(f"{id}. {film[0]} = {film[3]} Tiket")

    while True:
      try:
        choice = int(input("pilih film (1-5): "))
        if 1 <= choice <= 5:
          break
        else:
          print("Pilihan tidak valid")
      except ValueError:
        print("Masukkan angka 1-5")

    while True:
      try:
        num_tickets = int(input("Masukkan Jumlah tiket: "))
        if num_tickets > 0 and num_tickets <= dataFilm[choice][3]:
          break;
        else:
          print("Jumlah tiket tidak valid")
      except ValueError:
        print("Masukkan angka")

    total_price = num_tickets * dataFilm[choice][2] / 1000
    print(f"total harga: {total_price}")

while True:
    show_menu()
    choice = input("Masukkan pilihan : ")

    if choice == "1":
        show_movies(dataFilm)
    elif choice == "2":
        buy_tickets(dataFilm)
    elif choice == "3":
        print("Fitur Lihat Tiket belum tersedia.")
    elif choice == "4":
        print("Terima kasih, program selesai.")
        break
    else:
        print("pilihan tidak valid")

Menu:
1. Daftar Film
2. Beli Tiket
3. Lihat Tiket
4. Akhiri Program
Masukkan pilihan : 1
Daftar Film:
1. Deadpool & Wolverine - Jam 13:15 - Harga: 40000
2. Venom: The Last Ride - Jam 14:30 - Harga: 100000
3. Transformers: The One - Jam 15:00 - Harga: 55000
4. Mufasa The Lion King - Jam 17:20 - Harga: 35000
5. Gladiator II - Jam 17:45 - Harga: 55000
Menu:
1. Daftar Film
2. Beli Tiket
3. Lihat Tiket
4. Akhiri Program
Masukkan pilihan : 3
Fitur Lihat Tiket belum tersedia.
Menu:
1. Daftar Film
2. Beli Tiket
3. Lihat Tiket
4. Akhiri Program
Masukkan pilihan : 1
Daftar Film:
1. Deadpool & Wolverine - Jam 13:15 - Harga: 40000
2. Venom: The Last Ride - Jam 14:30 - Harga: 100000
3. Transformers: The One - Jam 15:00 - Harga: 55000
4. Mufasa The Lion King - Jam 17:20 - Harga: 35000
5. Gladiator II - Jam 17:45 - Harga: 55000
Menu:
1. Daftar Film
2. Beli Tiket
3. Lihat Tiket
4. Akhiri Program
Masukkan pilihan : 2
Tiket Tersedia:
1. Deadpool & Wolverine = 30 Tiket
2. Venom: The Last Ride = 35 Tiket
3. Transformers: The One = 35 Tiket
4. Mufasa The Lion King = 20 Tiket
5. Gladiator II = 40 Tiket
pilih film (1-5): 4
Masukkan Jumlah tiket: 45
Jumlah tiket tidak valid
Masukkan Jumlah tiket: 5
total harga: 175.0
Menu:
1. Daftar Film
2. Beli Tiket
3. Lihat Tiket
4. Akhiri Program
Masukkan pilihan : 2
Tiket Tersedia:
1. Deadpool & Wolverine = 30 Tiket
2. Venom: The Last Ride = 35 Tiket
3. Transformers: The One = 35 Tiket
4. Mufasa The Lion King = 20 Tiket
5. Gladiator II = 40 Tiket
pilih film (1-5): 4
Masukkan Jumlah tiket: 10
total harga: 350.0
Menu:
1. Daftar Film
2. Beli Tiket
3. Lihat Tiket
4. Akhiri Program
Masukkan pilihan : 2
Tiket Tersedia:
1. Deadpool & Wolverine = 30 Tiket
2. Venom: The Last Ride = 35 Tiket
3. Transformers: The One = 35 Tiket
4. Mufasa The Lion King = 20 Tiket
5. Gladiator II = 40 Tiket
pilih film (1-5): 4
Masukkan Jumlah tiket: 20
total harga: 700.0
Menu:
1. Daftar Film
2. Beli Tiket
3. Lihat Tiket
4. Akhiri Program
Masukkan pilihan : 2
Tiket Tersedia:
1. Deadpool & Wolverine = 30 Tiket
2. Venom: The Last Ride = 35 Tiket
3. Transformers: The One = 35 Tiket
4. Mufasa The Lion King = 20 Tiket
5. Gladiator II = 40 Tiket
pilih film (1-5): 4
Masukkan Jumlah tiket: 6
total harga: 210.0
Menu:
1. Daftar Film
2. Beli Tiket
3. Lihat Tiket
4. Akhiri Program
Masukkan pilihan : 4
Terima kasih, program selesai.